export const RedlightImage = {
  Bg_Img1: require('../assets/images/Rectangle1.png'),
  Bg_Img2: require('../assets/images/Group.png'),
  Bg_Img3: require('../assets/images/group12.png'),
  card: require('../assets/images/card_1.png'),
  Gift: require('../assets/icons/Gift.png'),
  addPic: require('../assets/images/addPic.png'),
  search: require('../assets/icons/Search.png'),
  sliderImager: require('../assets/icons/sliderImage.png'),
  ViewPlanBg: require('../assets/images/ViewPlanBg.png'),
  planBg: require('../assets/images/planBg.png'),
  On_switchs: require('../assets/icons/F_switchs.png'),
  Off_switchs: require('../assets/icons/F_switchs_off.png'),
  check_red: require('../assets/icons/check_red.png'),
  chat_Red: require('../assets/icons/m_chats.png'),
  chat_Red1: require('../assets/icons/Chat_popuv.png'),
  plusicon: require('../assets/icons/C_plus.png'),
};
export const ReddarkImage = {
  Bg_Img1: require('../assets/images/Bg_dark1.png'),
  Bg_Img2: require('../assets/images/Bg_dark2.png'),
  Bg_Img3: require('../assets/images/Bg_dark3.png'),
};
export const BluelightImage = {
  Bg_Img1: require('../assets/colorimages/blue/Bg1_blue.png'),
  Bg_Img2: require('../assets/colorimages/blue/Bg2_blue.png'),
  Bg_Img3: require('../assets/colorimages/blue/Bg3_blue.png'),
  card_blue: require('../assets/colorimages/blue/card_blue.png'),
  Gift_blue: require('../assets/colorimages/blue/Gift_blue.png'),
  addPic_blue: require('../assets/colorimages/blue/addPic_blue.png'),
  search_blue: require('../assets/colorimages/blue/search_blue.png'),
  sliderImage_bluer: require('../assets/colorimages/blue/sliderImage_bluer.png'),
  ViewPlanBg_blue: require('../assets/colorimages/blue/ViewPlanBg_blue.png'),
  planBg_blue: require('../assets/colorimages/blue/planBg_blue.png'),
  On_switchs_blue: require('../assets/colorimages/blue/on_switchs_blue.png'),
  Off_switchs_blue: require('../assets/colorimages/blue/off_switchs_blue.png'),
  check_blue: require('../assets/colorimages/blue/check_blue.png'),
  chat_blue: require('../assets/colorimages/blue/chat_blue.png'),
  chat_blue1: require('../assets/colorimages/blue/chat_blue1.png'),
  plusiconblue: require('../assets/colorimages/blue/C_plus_blue.png'),
};
export const GreenlightImage = {
  Bg_Img1: require('../assets/colorimages/green/Bg1_green.png'),
  Bg_Img2: require('../assets/colorimages/green/Bg2_green.png'),
  Bg_Img3: require('../assets/colorimages/green/Bg3_green.png'),
  card_green: require('../assets/colorimages/green/card_green.png'),
  Gift_green: require('../assets/colorimages/green/Gift_green.png'),
  addPic_green: require('../assets/colorimages/green/addPic_green.png'),
  search_green: require('../assets/colorimages/green/search_green.png'),
  sliderImage_green: require('../assets/colorimages/green/sliderImage_green.png'),
  ViewPlanBg_green: require('../assets/colorimages/green/ViewPlanBg_green.png'),
  planBg_green: require('../assets/colorimages/green/planBg_green.png'),
  On_switchs_green: require('../assets/colorimages/green/on_switchs_green.png'),
  Off_switchs_green: require('../assets/colorimages/green/off_switchs_green.png'),
  check_green: require('../assets/colorimages/green/check_green.png'),
  chat_green: require('../assets/colorimages/green/chat_green.png'),
  chat_green1: require('../assets/colorimages/green/chat_green1.png'),
  plusicongreen: require('../assets/colorimages/green/C_plus_green.png'),
};
export const PurplelightImage = {
  Bg_Img1: require('../assets/colorimages/purplle/Bg1_purple.png'),
  Bg_Img2: require('../assets/colorimages/purplle/Bg2_purple.png'),
  Bg_Img3: require('../assets/colorimages/purplle/Bg3_purple.png'),
  card_purple: require('../assets/colorimages/purplle/card_purple.png'),
  Gift_purple: require('../assets/colorimages/purplle/Gift_purple.png'),
  addPic_purple: require('../assets/colorimages/purplle/addPic_purple.png'),
  search_purple: require('../assets/colorimages/purplle/search_purple.png'),
  sliderImage_purple: require('../assets/colorimages/purplle/sliderImage_purple.png'),
  ViewPlanBg_purple: require('../assets/colorimages/purplle/ViewPlanBg_purple.png'),
  planBg_purple: require('../assets/colorimages/purplle/planBg_purple.png'),
  On_switchs_purplle: require('../assets/colorimages/purplle/on_switchs_purple.png'),
  Off_switchs_purplle: require('../assets/colorimages/purplle/off_switchs_purple.png'),
  check_purple: require('../assets/colorimages/purplle/check_purple.png'),
  chat_purple: require('../assets/colorimages/purplle/chat_purple.png'),
  chat_purple1: require('../assets/colorimages/purplle/chat_purple1.png'),
  plusiconpurple: require('../assets/colorimages/purplle/C_plus_purple.png'),
};
export const YellowlightImage = {
  Bg_Img1: require('../assets/colorimages/yellow/Bg1_yellow.png'),
  Bg_Img2: require('../assets/colorimages/yellow/Bg2_yellow.png'),
  Bg_Img3: require('../assets/colorimages/yellow/Bg3_yellow.png'),
  card_yellow: require('../assets/colorimages/yellow/card_yellow.png'),
  Gift_yellow: require('../assets/colorimages/yellow/Gift_yellow.png'),
  addPic_yellow: require('../assets/colorimages/yellow/addPic_yellow.png'),
  search_yellow: require('../assets/colorimages/yellow/search_yellow.png'),
  sliderImage_yellow: require('../assets/colorimages/yellow/sliderImage_yellow.png'),
  ViewPlanBg_yellow: require('../assets/colorimages/yellow/ViewPlanBg_yellow.png'),
  planBg_yellow: require('../assets/colorimages/yellow/planBg_yellow.png'),
  On_switchs_yellow: require('../assets/colorimages/yellow/on_switchs_yellow.png'),
  Off_switchs_yellow: require('../assets/colorimages/yellow/off_switchs_yellow.png'),
  check_yellow: require('../assets/colorimages/yellow/check_yellow.png'),
  chat_yellow: require('../assets/colorimages/yellow/chat_yellow.png'),
  chat_yellow1: require('../assets/colorimages/yellow/chat_yellow1.png'),
  plusiconyellow: require('../assets/colorimages/yellow/C_plus_yellow.png'),
};
